import React from 'react'

const TermsConditions = () => {
  return (
    <div className='bg-white'>
      <section>
        <div className="flex flex-col items-center justify-center px-5 md:px-10">
          {/* Title Container */}
          <div className="flex h-auto min-w-[100vw] flex-col items-center justify-end bg-[#f2f2f7] py-6 md:h-64">
            <div className="flex flex-col items-center gap-y-4 py-5">
              <h1 className="text-3xl font-bold md:text-5xl">TERMS AND CONDITIONS</h1>
              <p className="text-sm text-[#808080] sm:text-base">

              </p>
            </div>
          </div>
          {/* Content Container */}
          <div className="mx-auto w-full max-w-5xl py-12 md:py-16 lg:py-20">
            {/* Component */}
            <div className="flex flex-col items-center gap-y-14">

              <div className="flex min-w-full flex-col gap-y-10">

                <div className="flex flex-col gap-y-10">
                  <div className="flex min-w-full flex-col items-start gap-y-6">
                    <div className="flex flex-col items-start gap-y-3">
                      <p className="text-sm font-bold">Terms & Conditions</p>
                      <p className="text-sm">
                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        <br />
                        <br />
                        his document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of careers.padme.com, life. padme.com & blog.padme.com website.
                        <br />
                        <br />
                        This Website, including all Materials present (excluding any applicable third party materials), is the property of Myntra and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws worldwide in Your use of this Website and to prevent any unauthorized copying of the Materials.
                        <br />
                        <br />
                        By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree to take all of the terms and conditions stated on this page.
                        <br />
                        <br />
                        The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves.

                      </p>
                    </div>
                    <div className="flex flex-col items-start gap-y-3">
                      <p className="text-sm font-bold">Cookies</p>
                      <p className="text-sm">
                        We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy Policy.
                        <br />
                        <br />
                        Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.
                      </p>
                    </div>
                    <div className="flex flex-col items-start gap-y-3">
                      <p className="text-sm font-bold">License</p>
                      <p className="text-sm">
                        Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name. All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to restrictions set in these terms and conditions.
                        <br />
                        <br />
                        1. Republish material from Website Name
                        <br />
                        2. Sell, rent or sub-license material from Website Name
                        <br />
                        3. Reproduce, duplicate or copy material from Website Name
                        <br />
                        4. Redistribute content from Website Name
                        <br />
                        <br />
                        This agreement Shall begin on the date hereof.
                        <br />
                        <br />
                        Parts of this Website offer an opportunity for users to post and exchange opinions and information in certain areas of the Website. Company Name does not filter, edit, publish or review comments prior to their presence on the website. Comments do not reflect the views and opinions of the person who post their views and opinions.
                        <br />
                        <br />
                        Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.
                        <br />
                        <br />
                        Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.
                      </p>
                    </div>
                    
                   
                   
                    
                    
                  </div>
                  <div className="min-h-[1px] min-w-full bg-[#e2e2e2]" />
                 
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>



    </div>
  )
}

export default TermsConditions;
