import React from 'react'

const TermsConditions = () => {
  return (
    <div>
    <>
  <meta charSet="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
    rel="stylesheet"
  />
  <style
    dangerouslySetInnerHTML={{
      __html:
        "\n    .fade-in {\n      animation: fadeIn 0.8s ease-in-out;\n    }\n    @keyframes fadeIn {\n      from { opacity: 0; transform: translateY(20px); }\n      to { opacity: 1; transform: translateY(0); }\n    }\n  "
    }}
  />
  {/* Main Content */}
  <main className="flex-grow max-w-4xl mx-auto px-6 py-12 fade-in">
    <section className="bg-white shadow-2xl rounded-3xl p-8">
      <h2 className="text-3xl font-bold text-indigo-700 mb-6 text-center">
        📜 Terms &amp; Conditions
      </h2>
      {/* Section 1 */}
      <div className="mb-8">
        <h3 className="text-2xl font-semibold text-indigo-600 mb-2">
        Terms and Conditions
        </h3>
        <p className="text-gray-700 leading-relaxed">
          This document is an electronic record in terms of information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          <br />
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of careers.padme.com, life.padme.com & blog.padme.com website.
          <br />
          This Website, including all Materials present (excluding any applicable third party Materials), is the property of Myntra and is copyrighted and protected by worldwide copyright laws and treaty provisions. You hereby agree to comply with all copyright laws worldwide in your use of this Website and to prevent any unauthorized copying of the Materials.
          <br />
          By accessing this website we assume you accept these terms and conditions. Do not continue to use website Name if you do not agree to take all of the terms and conditions stated on this page.
          <br />
          The following terminology applies to these Terms and Conditions, P
        </p>
      </div>
      {/* Section 2 */}
      <div className="mb-8">
        <h3 className="text-2xl font-semibold text-indigo-600 mb-2">
          2. Membership Eligibility
        </h3>
        <p className="text-gray-700 leading-relaxed">
          Membership is open to currently enrolled students. You may be required
          to provide proof of enrollment or identity when participating in
          official events or activities.
        </p>
      </div>
      {/* Section 3 */}
      <div className="mb-8">
        <h3 className="text-2xl font-semibold text-indigo-600 mb-2">
          3. Code of Conduct
        </h3>
        <p className="text-gray-700 leading-relaxed">
          All members are expected to behave respectfully towards others.
          Discrimination, harassment, or misconduct will not be tolerated and
          may result in suspension or expulsion.
        </p>
      </div>
      {/* Section 4 */}
      <div className="mb-8">
        <h3 className="text-2xl font-semibold text-indigo-600 mb-2">
          4. Event Participation
        </h3>
        <p className="text-gray-700 leading-relaxed">
          By attending events, you consent to photography and videography that
          may be used for promotional purposes. Participation is voluntary, and
          some events may have additional terms.
        </p>
      </div>
      {/* Section 5 */}
      <div className="mb-8">
        <h3 className="text-2xl font-semibold text-indigo-600 mb-2">
          5. Changes to Terms
        </h3>
        <p className="text-gray-700 leading-relaxed">
          We reserve the right to modify these terms at any time. Changes will
          be effective immediately upon posting on the website. It is your
          responsibility to review the terms regularly.
        </p>
      </div>
      {/* Contact Info */}
      <div className="text-center mt-10">
        <p className="text-gray-600 text-sm">
          For any questions or concerns regarding these terms, please contact us
          at{" "}
          <a
            href="mailto:club@college.edu"
            className="text-indigo-600 hover:underline"
          >
            club@college.edu
          </a>
          .
        </p>
      </div>
    </section>
  </main>
  {/* Footer */}
  <footer className="bg-white py-6 text-center text-sm text-gray-500 shadow-inner">
    © 2025 College Club. All rights reserved.
  </footer>
</>

    </div>
  )
}

export default TermsConditions;
